name: ChatClearPE
main: BeeAZZ\ChatClearPE\Main
api: 5.0.0
version: 0.0.3
author: BeeAZ
description: Clean up chats with just one command or auto

commands:
 clearchat:
  description: Clear Chat Command
  aliases: ["cc"]
  permission: chatclearpe.command
permissions:
 chatclearpe.command:
  default: op
